import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container, ThemeProvider, createTheme } from "@mui/material";
import { Navbar } from "./components/navbar";
import { sofiaSans } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  typography: {
    fontFamily: sofiaSans.style.fontFamily,
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sofiaSans.className} scrollbar`}>
        <ThemeProvider theme={theme}>
          <Container>
            <Navbar />
            <main>{children}</main>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
